//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 09:24:53 PM CST 
//


package bh.toolkit.srcgen.model.mybatis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Collection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Collection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="constructor" type="{http://slp/toolkit/ormgen/model/mybatis}Constructor" minOccurs="0"/>
 *         &lt;element name="id" type="{http://slp/toolkit/ormgen/model/mybatis}Id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="result" type="{http://slp/toolkit/ormgen/model/mybatis}Result" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="association" type="{http://slp/toolkit/ormgen/model/mybatis}Association" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="collection" type="{http://slp/toolkit/ormgen/model/mybatis}Collection" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="discriminator" type="{http://slp/toolkit/ormgen/model/mybatis}Discriminator" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="javaType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ofType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jdbcType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="select" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultMap" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="typeHandler" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="notNullColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="columnPrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultSet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="foreignColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autoMapping">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fetchType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="lazy"/>
 *             &lt;enumeration value="eager"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Collection", propOrder = {
    "constructor",
    "id",
    "result",
    "association",
    "collection",
    "discriminator"
})
public class Collection {

    protected Constructor constructor;
    protected List<Id> id;
    protected List<Result> result;
    protected List<Association> association;
    protected List<Collection> collection;
    protected Discriminator discriminator;
    @XmlAttribute(name = "property", required = true)
    protected String property;
    @XmlAttribute(name = "column")
    protected String column;
    @XmlAttribute(name = "javaType")
    protected String javaType;
    @XmlAttribute(name = "ofType")
    protected String ofType;
    @XmlAttribute(name = "jdbcType")
    protected String jdbcType;
    @XmlAttribute(name = "select")
    protected String select;
    @XmlAttribute(name = "resultMap")
    protected String resultMap;
    @XmlAttribute(name = "typeHandler")
    protected String typeHandler;
    @XmlAttribute(name = "notNullColumn")
    protected String notNullColumn;
    @XmlAttribute(name = "columnPrefix")
    protected String columnPrefix;
    @XmlAttribute(name = "resultSet")
    protected String resultSet;
    @XmlAttribute(name = "foreignColumn")
    protected String foreignColumn;
    @XmlAttribute(name = "autoMapping")
    protected String autoMapping;
    @XmlAttribute(name = "fetchType")
    protected String fetchType;

    /**
     * Gets the value of the constructor property.
     * 
     * @return
     *     possible object is
     *     {@link Constructor }
     *     
     */
    public Constructor getConstructor() {
        return constructor;
    }

    /**
     * Sets the value of the constructor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constructor }
     *     
     */
    public void setConstructor(Constructor value) {
        this.constructor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Id }
     * 
     * 
     */
    public List<Id> getId() {
        if (id == null) {
            id = new ArrayList<Id>();
        }
        return this.id;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Result }
     * 
     * 
     */
    public List<Result> getResult() {
        if (result == null) {
            result = new ArrayList<Result>();
        }
        return this.result;
    }

    /**
     * Gets the value of the association property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the association property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Association }
     * 
     * 
     */
    public List<Association> getAssociation() {
        if (association == null) {
            association = new ArrayList<Association>();
        }
        return this.association;
    }

    /**
     * Gets the value of the collection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the collection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCollection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Collection }
     * 
     * 
     */
    public List<Collection> getCollection() {
        if (collection == null) {
            collection = new ArrayList<Collection>();
        }
        return this.collection;
    }

    /**
     * Gets the value of the discriminator property.
     * 
     * @return
     *     possible object is
     *     {@link Discriminator }
     *     
     */
    public Discriminator getDiscriminator() {
        return discriminator;
    }

    /**
     * Sets the value of the discriminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discriminator }
     *     
     */
    public void setDiscriminator(Discriminator value) {
        this.discriminator = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperty(String value) {
        this.property = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the javaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaType() {
        return javaType;
    }

    /**
     * Sets the value of the javaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaType(String value) {
        this.javaType = value;
    }

    /**
     * Gets the value of the ofType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfType() {
        return ofType;
    }

    /**
     * Sets the value of the ofType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfType(String value) {
        this.ofType = value;
    }

    /**
     * Gets the value of the jdbcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcType() {
        return jdbcType;
    }

    /**
     * Sets the value of the jdbcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcType(String value) {
        this.jdbcType = value;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelect(String value) {
        this.select = value;
    }

    /**
     * Gets the value of the resultMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultMap() {
        return resultMap;
    }

    /**
     * Sets the value of the resultMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultMap(String value) {
        this.resultMap = value;
    }

    /**
     * Gets the value of the typeHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeHandler() {
        return typeHandler;
    }

    /**
     * Sets the value of the typeHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeHandler(String value) {
        this.typeHandler = value;
    }

    /**
     * Gets the value of the notNullColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotNullColumn() {
        return notNullColumn;
    }

    /**
     * Sets the value of the notNullColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotNullColumn(String value) {
        this.notNullColumn = value;
    }

    /**
     * Gets the value of the columnPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnPrefix() {
        return columnPrefix;
    }

    /**
     * Sets the value of the columnPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnPrefix(String value) {
        this.columnPrefix = value;
    }

    /**
     * Gets the value of the resultSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultSet() {
        return resultSet;
    }

    /**
     * Sets the value of the resultSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultSet(String value) {
        this.resultSet = value;
    }

    /**
     * Gets the value of the foreignColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignColumn() {
        return foreignColumn;
    }

    /**
     * Sets the value of the foreignColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignColumn(String value) {
        this.foreignColumn = value;
    }

    /**
     * Gets the value of the autoMapping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoMapping() {
        return autoMapping;
    }

    /**
     * Sets the value of the autoMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoMapping(String value) {
        this.autoMapping = value;
    }

    /**
     * Gets the value of the fetchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFetchType() {
        return fetchType;
    }

    /**
     * Sets the value of the fetchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFetchType(String value) {
        this.fetchType = value;
    }

}
