//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 09:24:53 PM CST 
//


package bh.toolkit.srcgen.model.mybatis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Update complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Update">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="selectKey" type="{http://slp/toolkit/ormgen/model/mybatis}SelectKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="include" type="{http://slp/toolkit/ormgen/model/mybatis}Include" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cDataBegin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trim" type="{http://slp/toolkit/ormgen/model/mybatis}Trim" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="where" type="{http://slp/toolkit/ormgen/model/mybatis}Where" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="set" type="{http://slp/toolkit/ormgen/model/mybatis}Set" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="foreach" type="{http://slp/toolkit/ormgen/model/mybatis}Foreach" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="choose" type="{http://slp/toolkit/ormgen/model/mybatis}Choose" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="if" type="{http://slp/toolkit/ormgen/model/mybatis}If" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bind" type="{http://slp/toolkit/ormgen/model/mybatis}Bind" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cDataEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parameterMap" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parameterType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flushCache">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="statementType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="STATEMENT"/>
 *             &lt;enumeration value="PREPARED"/>
 *             &lt;enumeration value="CALLABLE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="keyProperty" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useGeneratedKeys">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="keyColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="databaseId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Update", propOrder = {
    "selectKey",
    "include",
    "cDataBegin",
    "trim",
    "where",
    "set",
    "foreach",
    "choose",
    "_if",
    "bind",
    "cDataEnd"
})
public class Update {

    protected List<SelectKey> selectKey;
    protected List<Include> include;
    protected String cDataBegin;
    protected List<Trim> trim;
    protected List<Where> where;
    protected List<Set> set;
    protected List<Foreach> foreach;
    protected List<Choose> choose;
    @XmlElement(name = "if")
    protected List<If> _if;
    protected List<Bind> bind;
    protected String cDataEnd;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "parameterMap")
    protected String parameterMap;
    @XmlAttribute(name = "parameterType")
    protected String parameterType;
    @XmlAttribute(name = "timeout")
    protected String timeout;
    @XmlAttribute(name = "flushCache")
    protected String flushCache;
    @XmlAttribute(name = "statementType")
    protected String statementType;
    @XmlAttribute(name = "keyProperty")
    protected String keyProperty;
    @XmlAttribute(name = "useGeneratedKeys")
    protected String useGeneratedKeys;
    @XmlAttribute(name = "keyColumn")
    protected String keyColumn;
    @XmlAttribute(name = "databaseId")
    protected String databaseId;
    @XmlAttribute(name = "lang")
    protected String lang;

    /**
     * Gets the value of the selectKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectKey }
     * 
     * 
     */
    public List<SelectKey> getSelectKey() {
        if (selectKey == null) {
            selectKey = new ArrayList<SelectKey>();
        }
        return this.selectKey;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * 
     * 
     */
    public List<Include> getInclude() {
        if (include == null) {
            include = new ArrayList<Include>();
        }
        return this.include;
    }

    /**
     * Gets the value of the cDataBegin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDataBegin() {
        return cDataBegin;
    }

    /**
     * Sets the value of the cDataBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDataBegin(String value) {
        this.cDataBegin = value;
    }

    /**
     * Gets the value of the trim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trim }
     * 
     * 
     */
    public List<Trim> getTrim() {
        if (trim == null) {
            trim = new ArrayList<Trim>();
        }
        return this.trim;
    }

    /**
     * Gets the value of the where property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the where property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWhere().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Where }
     * 
     * 
     */
    public List<Where> getWhere() {
        if (where == null) {
            where = new ArrayList<Where>();
        }
        return this.where;
    }

    /**
     * Gets the value of the set property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the set property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Set }
     * 
     * 
     */
    public List<Set> getSet() {
        if (set == null) {
            set = new ArrayList<Set>();
        }
        return this.set;
    }

    /**
     * Gets the value of the foreach property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foreach property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForeach().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Foreach }
     * 
     * 
     */
    public List<Foreach> getForeach() {
        if (foreach == null) {
            foreach = new ArrayList<Foreach>();
        }
        return this.foreach;
    }

    /**
     * Gets the value of the choose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the choose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChoose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Choose }
     * 
     * 
     */
    public List<Choose> getChoose() {
        if (choose == null) {
            choose = new ArrayList<Choose>();
        }
        return this.choose;
    }

    /**
     * Gets the value of the if property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the if property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link If }
     * 
     * 
     */
    public List<If> getIf() {
        if (_if == null) {
            _if = new ArrayList<If>();
        }
        return this._if;
    }

    /**
     * Gets the value of the bind property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bind property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBind().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bind }
     * 
     * 
     */
    public List<Bind> getBind() {
        if (bind == null) {
            bind = new ArrayList<Bind>();
        }
        return this.bind;
    }

    /**
     * Gets the value of the cDataEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDataEnd() {
        return cDataEnd;
    }

    /**
     * Sets the value of the cDataEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDataEnd(String value) {
        this.cDataEnd = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parameterMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterMap() {
        return parameterMap;
    }

    /**
     * Sets the value of the parameterMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterMap(String value) {
        this.parameterMap = value;
    }

    /**
     * Gets the value of the parameterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterType() {
        return parameterType;
    }

    /**
     * Sets the value of the parameterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterType(String value) {
        this.parameterType = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the flushCache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlushCache() {
        return flushCache;
    }

    /**
     * Sets the value of the flushCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlushCache(String value) {
        this.flushCache = value;
    }

    /**
     * Gets the value of the statementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatementType() {
        return statementType;
    }

    /**
     * Sets the value of the statementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatementType(String value) {
        this.statementType = value;
    }

    /**
     * Gets the value of the keyProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyProperty() {
        return keyProperty;
    }

    /**
     * Sets the value of the keyProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyProperty(String value) {
        this.keyProperty = value;
    }

    /**
     * Gets the value of the useGeneratedKeys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseGeneratedKeys() {
        return useGeneratedKeys;
    }

    /**
     * Sets the value of the useGeneratedKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseGeneratedKeys(String value) {
        this.useGeneratedKeys = value;
    }

    /**
     * Gets the value of the keyColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyColumn() {
        return keyColumn;
    }

    /**
     * Sets the value of the keyColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyColumn(String value) {
        this.keyColumn = value;
    }

    /**
     * Gets the value of the databaseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseId() {
        return databaseId;
    }

    /**
     * Sets the value of the databaseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseId(String value) {
        this.databaseId = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
